### ISSUE TITLE
Create a drag feature

### ISSUE THREAD

**Issue by MasakoOllivier** [MasakoOllivier/nonogram-puzzle#6]

**Comment by kollivier** [comment]
To mark / unmark the cells in real time as you drag over them, you can add an event listener for the `mouseenter` event. This event fires whenever the mouse enters a particular HTML element.

When you handle this event, you need to check two things:

1. That you're in a cell (i.e. has an id like `c1r2`, rather than `puzzleboard`)
2. That the event's `.button` value is set to 1 (that's mouse button 1, or typically, the left mouse button) before you mark / unmark the cell.

Here are the mouseenter docs:

https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event

**Comment by MasakoOllivier** [comment]
When I drag from right to left, and from a lower cell to a higher cell,  it doesn't mark the range grey.

**Comment by kollivier** [comment]
@MasakoOllivier Is that when you use `mouseenter`, or when you use the existing approach with `mouseup`?

The `mouseup` approach would need to flip the start and end cells to work when you're going the opposite way. Using `mouseenter` would make this unnecessary, though, and would also allow the cell to be marked as soon as the mouse enters the new cell.
